apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: server
        image: local/grpc-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: LISTEN_ADDR
          value: ":50051"

